name: mydayplanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.7.2
  http: ^1.4.0
  provider: ^6.1.5
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  bcrypt: ^1.1.3
  get_storage: ^2.1.1
  flutter_localization: ^0.3.2
  flutter_rounded_date_picker: ^3.0.4
  intl: ^0.20.2
  shimmer: ^3.0.0
  recaptcha_enterprise_flutter: ^18.7.1
  firebase_app_check: ^0.3.2+6
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  marquee: ^2.3.0
  fl_chart: ^1.0.0
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/aleart/
    - assets/config/
    - assets/text/
    - .env
  fonts:
    - family: baloo
      fonts:
        - asset: assets/fonts/Baloo2-Bold.ttf
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
        - asset: assets/fonts/Baloo2-Medium.ttf
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-SemiBold.ttf
    - family: mali
      fonts:
        - asset: assets/fonts/Mali-Bold.ttf
        - asset: assets/fonts/Mali-Medium.ttf
        - asset: assets/fonts/Mali-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoApp.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/LogoApp.png"