name: mydayplanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.6.6
  http: ^1.2.2
  provider: ^6.1.2
  path_provider: ^2.1.5
  flutter_svg: ^2.0.16
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  webview_flutter: ^4.10.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  bcrypt: ^1.1.3
  get_storage: ^2.1.1
  flutter_localization: ^0.3.0
  flutter_rounded_date_picker: ^3.0.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  recaptcha_enterprise_flutter: ^18.7.0
  firebase_app_check: ^0.3.2+4
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.14.3
  marquee: ^2.2.3
  fl_chart: ^0.71.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/aleart/
    - assets/config/
    - assets/text/
    - .env
  fonts:
    - family: baloo
      fonts:
        - asset: assets/fonts/Baloo2-Bold.ttf
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
        - asset: assets/fonts/Baloo2-Medium.ttf
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-SemiBold.ttf
    - family: mali
      fonts:
        - asset: assets/fonts/Mali-Bold.ttf
        - asset: assets/fonts/Mali-Medium.ttf
        - asset: assets/fonts/Mali-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoApp.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/LogoApp.png"