// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzyP8oUyoXWAws_xVg-NAcBRM6jySa0Nc',
    appId: '1:773568755866:android:00397cf859e18d6c828723',
    messagingSenderId: '773568755866',
    projectId: 'mydayplanner-a6270',
    storageBucket: 'mydayplanner-a6270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE3glIo46ku_YXzH75LyhqpN1yNHF2bO4',
    appId: '1:773568755866:ios:81d27d8a65d76026828723',
    messagingSenderId: '773568755866',
    projectId: 'mydayplanner-a6270',
    storageBucket: 'mydayplanner-a6270.firebasestorage.app',
    androidClientId: '773568755866-e4t9lp0g4blt2qplifr8bnlftti19rnb.apps.googleusercontent.com',
    iosClientId: '773568755866-kb3m2p7skb2k9ecj6475egrrp628bn0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.demomydayplanner',
  );
}
